### ISSUE TITLE
Android - Error Unity DllNotFoundException: Unable to load DLL 'mediapipe_jni'

### ISSUE THREAD

**Issue by FUBAR2077** [homuler/MediaPipeUnityPlugin#269]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): Microsoft Windows [Version 10.0.19042.1165]
- Target Platform: Android
- Mobile Device (if the target is Android or iOS): Samsung Galaxy S7
- MediaPipeUnityPlugin version or commit id: d58ab72c8149fce183ce804aef2e218f74ff70dc
- Bazel version: -
- GCC/G++ version: -
- Android NDK version (if the target platform is Android): 19.0.5232133
- Xcode version (if the target platform is iOS):

**Describe the current behavior**
I've built all dll's with docker, everything started to work on Windows, but when I build to Android it does not work on my Galaxy S7. Error that I get is:
![image](https://user-images.githubusercontent.com/4373019/132248038-b533431f-e2f2-48c5-b822-ec0429ca2bfe.png)

and 

![image](https://user-images.githubusercontent.com/4373019/132248050-9e42bf0b-f3cd-42af-bf2e-e1f54fc50bf9.png)

when using ADB to see what happens.

Is there any tips for this @homuler? 
mediapipe_android.aar looks fine after building and it works on Desktop. I have Load on startup enabled on libmediapipe_c.dll and opencv_world3410.dll.
I have "Use GPU" marked as well when building for Android.

I have only those in Streaming Assets, and not much more assetbundles, but nothing else appears when I do Assets>Build AssetBundles:
![image](https://user-images.githubusercontent.com/4373019/132248702-cf9cc79d-a584-4a55-83df-63f0508c0fa1.png)

I also have those libs in .apk:
![image](https://user-images.githubusercontent.com/4373019/132249140-08b54e49-c792-4886-b314-96a4f1256530.png)

**Comment by FUBAR2077** [comment]
For everyone having this problem in the future -

It was a two-stepper so pretty hard to find and combine but here it is:

Before you build android library with docker you need to edit WORKSPACE file to include NDK api_level like this (according to this comment: https://github.com/google/mediapipe/issues/1224#issuecomment-745190852) :

# You may run setup_android.sh to install Android SDK and NDK.
android_ndk_repository(
    name = "androidndk",
	api_level = 21,
)

@homuler can we edit WORSPACE file like this ^ for everyone? I can make my first MR for this :)

and another important thing is that to have proper assetbundles build is to have properly configured meta files of *.bytes files that you have in Packages\com.github.homuler.mediapipe\Runtime\Resources folder.
By proper I mean editing them from this (I have checked diff according to this comment: https://github.com/homuler/MediaPipeUnityPlugin/issues/119#issuecomment-815650602 and I noticed it has been removed on import):

```
fileFormatVersion: 2
guid: eccb5de6967da1d4b80280b079b3ec2b
TextScriptImporter:
  externalObjects: {}
  userData: 
  assetBundleName:
  assetBundleVariant: 
```
to this:
```
fileFormatVersion: 2
guid: eccb5de6967da1d4b80280b079b3ec2b
TextScriptImporter:
  externalObjects: {}
  userData: 
  assetBundleName: mediapipe
  assetBundleVariant: 
```
and then do Assets>Build AssetBundles from the menu and you should be good to go :)
